version: '2'
services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: boxes
      POSTGRES_DB: boxes
  web:
    depends_on:
      - postgres
    build: .
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://boxes@postgres/boxes
      NODE_ENV: development
    command: npm run dev
